// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 RS-Key contributors

//! Generates the width-4 Lim–Lee fixed-base comb tables `ec.rs` uses for
//! `k·G` / `d·G` — one per curve that signs through the comb (P-256 and P-521,
//! ~2× / ~4× on the in-order Cortex-M33). Each entry is
//! `T[i] = Σ_{j ∈ set-bits(i)} 2^{j·D}·G` (`D = ceil(bits/4)`) as affine
//! big-endian bytes; `T[0]` is an identity sentinel the runtime comb never adds.
//! Each table is KAT-checked at runtime against `mul_by_generator` (see `ec.rs`).

use std::env;
use std::fs;
use std::path::Path;

const W: usize = 4;

macro_rules! gen_comb {
    ($curve:ident, $d:expr, $coord:expr, $constname:literal, $file:literal) => {{
        use $curve::ProjectivePoint;
        use $curve::elliptic_curve::sec1::ToEncodedPoint;

        // base[j] = 2^{j·D}·G, by repeated doubling of the generator.
        let mut base = [ProjectivePoint::GENERATOR; W];
        for j in 1..W {
            let mut p = base[j - 1];
            for _ in 0..$d {
                p += p;
            }
            base[j] = p;
        }

        // T[i] = Σ_{j ∈ set-bits(i)} base[j].
        let mut body = String::new();
        for i in 0..(1usize << W) {
            let (x, y) = if i == 0 {
                ([0u8; $coord], [0u8; $coord]) // identity sentinel — never added at runtime
            } else {
                let mut acc = ProjectivePoint::IDENTITY;
                for (j, b) in base.iter().enumerate() {
                    if i & (1 << j) != 0 {
                        acc += *b;
                    }
                }
                let ep = acc.to_affine().to_encoded_point(false);
                let mut x = [0u8; $coord];
                let mut y = [0u8; $coord];
                x.copy_from_slice(ep.x().expect("affine x"));
                y.copy_from_slice(ep.y().expect("affine y"));
                (x, y)
            };
            body.push_str(&format!("    ({x:?}, {y:?}),\n"));
        }

        let src = format!(
            "// Generated by build.rs — width-{W} comb table (D = {d}).\n\
             pub(crate) const {name}: [([u8; {c}], [u8; {c}]); {n}] = [\n{body}];\n",
            d = $d,
            name = $constname,
            c = $coord,
            n = 1usize << W,
        );
        let dst = Path::new(&env::var("OUT_DIR").unwrap()).join($file);
        fs::write(dst, src).expect("write comb table");
    }};
}

fn main() {
    gen_comb!(p521, 131, 66, "GEN_COMB", "gen_comb_p521.rs"); // ceil(521/4) = 131
    gen_comb!(p256, 64, 32, "GEN_COMB_P256", "gen_comb_p256.rs"); // ceil(256/4) = 64
    println!("cargo:rerun-if-changed=build.rs");
}
