// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 RS-Key contributors

//! Generates the P-521 width-4 Lim–Lee comb table `ec.rs` uses for fixed-base
//! `k·G` / `d·G` (~521 → ~131 doublings, ~4× on Cortex-M33). Each entry is
//! `T[i] = Σ_{j ∈ set-bits(i)} 2^{j·D}·G` (`D = ceil(521/4) = 131`) as affine
//! big-endian bytes; `T[0]` is an identity sentinel the runtime comb never adds.
//! The table is KAT-checked at runtime against `mul_by_generator` (see `ec.rs`).

use std::env;
use std::fs;
use std::path::Path;

use p521::ProjectivePoint;
use p521::elliptic_curve::sec1::ToEncodedPoint;

const W: usize = 4;
const D: usize = 131; // ceil(521 / 4)

fn main() {
    // base[j] = 2^{j·D}·G, by repeated doubling of the generator.
    let mut base = [ProjectivePoint::GENERATOR; W];
    for j in 1..W {
        let mut p = base[j - 1];
        for _ in 0..D {
            p += p;
        }
        base[j] = p;
    }

    // T[i] = Σ_{j ∈ set-bits(i)} base[j].
    let mut body = String::new();
    for i in 0..(1usize << W) {
        let (x, y) = if i == 0 {
            ([0u8; 66], [0u8; 66]) // identity sentinel — never added at runtime
        } else {
            let mut acc = ProjectivePoint::IDENTITY;
            for (j, b) in base.iter().enumerate() {
                if i & (1 << j) != 0 {
                    acc += *b;
                }
            }
            let ep = acc.to_affine().to_encoded_point(false);
            let mut x = [0u8; 66];
            let mut y = [0u8; 66];
            x.copy_from_slice(ep.x().expect("affine x"));
            y.copy_from_slice(ep.y().expect("affine y"));
            (x, y)
        };
        body.push_str(&format!("    ({x:?}, {y:?}),\n"));
    }

    let src = format!(
        "// Generated by build.rs — P-521 width-{W} comb table (D = {D}).\n\
         pub(crate) const GEN_COMB: [([u8; 66], [u8; 66]); {}] = [\n{body}];\n",
        1usize << W,
    );
    let dst = Path::new(&env::var("OUT_DIR").unwrap()).join("gen_comb_p521.rs");
    fs::write(dst, src).expect("write comb table");
    println!("cargo:rerun-if-changed=build.rs");
}
